language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

addons:
  apt:
    packages:
      - parallel
      - oracle-java8-installer
      - oracle-java8-set-default

jdk:
  - oraclejdk8

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - TYPO3_DATABASE_NAME="typo3_ci"
    - TYPO3_DATABASE_HOST="localhost"
    - TYPO3_DATABASE_USERNAME="root"
    - TYPO3_DATABASE_PASSWORD=""
    - EXT_SOLR_VERSION="dev-master"
  matrix:
    - TYPO3_VERSION="~7.6.14"
    - TYPO3_VERSION="7.x-dev"
    - TYPO3_VERSION="dev-master"

matrix:
  fast_finish: true
  exclude:
    - php: 5.5
      env: TYPO3_VERSION="dev-master"
    - php: 5.6
      env: TYPO3_VERSION="dev-master"
    - php: 5.5
      env: TYPO3_VERSION="~8.5.0"
    - php: 5.6
      env: TYPO3_VERSION="~8.5.0"
    - php: 7.1
      env: TYPO3_VERSION="7.x-dev"
    - php: 7.1
      env: TYPO3_VERSION="~7.6.14"
    - php: 7.1
      env: TYPO3_VERSION="~8.5.0"

before_install:
  - composer self-update
  - composer --version
  - composer global require friendsofphp/php-cs-fixer:v1.11.7
  - composer global require namelesscoder/typo3-repository-client
  # set root password
  - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('')"

install:
  - Build/Test/bootstrap.sh
script:
  - Build/Test/cibuild.sh
after_script:
  - Build/Test/cleanup.sh

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/solr/downloads
