# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2009-2015
  project: Apache Solr for TYPO3 - Enterprise Search
  version: 1.1
  release: 1.1.0
  latex_documents:
  - - Index
    - solr.tex
    - Apache Solr for TYPO3 - Result Grouping
    - Ingo Renner
    - manual
  html_theme_options:
      github_repository: TYPO3-Solr/ext-solrgrouping
      github_branch: master
    latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
...
